apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-worker
  namespace: telemetry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-worker
  template:
    metadata:
      labels:
        app: telemetry-worker
    spec:
      serviceAccountName: telemetry-worker-sa
      containers:
      - name: worker
        image: 370613533360.dkr.ecr.ap-south-1.amazonaws.com/worker:latest
        envFrom:
        - secretRef:
            name: telemetry-secret
        - configMapRef:
            name: telemetry-config
