name: Build and Push Images

on:
  push:
    branches:
      - main

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build API image
        run: |
          docker build \
            -f Dockerfile.api \
            -t api:${{ github.sha }} .

      - name: Tag API image
        run: |
          docker tag api:${{ github.sha }} \
          370613533360.dkr.ecr.ap-south-1.amazonaws.com/api:${{ github.sha }}

      - name: Push API image
        run: |
          docker push \
          370613533360.dkr.ecr.ap-south-1.amazonaws.com/api:${{ github.sha }}

  worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Worker image
        run: |
          docker build \
            -f Dockerfile.worker \
            -t worker:${{ github.sha }} .

      - name: Tag Worker image
        run: |
          docker tag worker:${{ github.sha }} \
          370613533360.dkr.ecr.ap-south-1.amazonaws.com/worker:${{ github.sha }}

      - name: Push Worker image
        run: |
          docker push \
          370613533360.dkr.ecr.ap-south-1.amazonaws.com/worker:${{ github.sha }}
